# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: Install EB CLI
description: Installs the Elastic Beanstalk CLI to the GitHub Actions runner
inputs:
  version:
    description: Version of the EB CLI that will be installed (such as 3.20.3).  Will default to latest if not specified.
    required: false
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        repository: 'aws/aws-elastic-beanstalk-cli-setup'
        path: 'aws-elastic-beanstalk-cli-setup'

    - uses: actions/setup-python@v5
      with:
        # https://github.com/aws/aws-elastic-beanstalk-cli/issues/493
        python-version: '3.11.x'

    - name: Pip install virtualenv
      shell: bash
      run: pipx install virtualenv

    - name: Install latest EB CLI version
      if: "${{ inputs.version == '' }}"
      run: python $GITHUB_WORKSPACE/aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py
      shell: bash

    - name: Install specific EB CLI version
      if: "${{ inputs.version != '' }}"
      run: python $GITHUB_WORKSPACE/aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py --version ${{ inputs.version }}
      shell: bash

    - name: Add eb to github GITHUB_PATH
      run: echo "~/.ebcli-virtual-env/executables" >> $GITHUB_PATH
      shell: bash
